mabs_exceptionizer:
    exceptions:
        mabs_exceptionizer.base_exception:
            class: Mabs\ExceptionizerBundle\Exception\BaseException
            arguments:
                message: "test exception"
                code:  100
        access_denied_excetion:
            class: Symfony\Component\Security\Core\Exception\AccessDeniedException
        not_found_http_exception:
            class: Symfony\Component\HttpKernel\Exception\NotFoundHttpException
