mabs_exceptionizer:
    exceptions:
        mabs_exceptionizer.base_exception:
            class: Mabs\ExceptionizerBundle\Exception\BaseException
            arguments:
                message: "test exception"
                code:  100
